export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'
export { default as Cart } from './Cart/Cart'
export { default as Home } from './Home/Home'
export { default as Product } from './Product/Product'
